export const FACULTY_NAMES = {
    "CN Hóa học và Thực phẩm" : ["CN Hóa học", "và Thực phẩm"],
    "Công nghệ Thông tin": ["Công nghệ", "Thông tin"],
    "Cơ Khí Chế Tạo Máy": ["Cơ Khí", "Chế Tạo Máy"],
    "Cơ Khí Động Lực": ["Cơ Khí", "Động Lực"],
    "In và Truyền thông": ["In và", "Truyền thông"],
    "Khoa học ứng dụng": ["Khoa học", "ứng dụng"],
    "Kinh tế": ["Kinh tế"],
    "Ngoại ngữ": ["Ngoại ngữ"],
    "Thời trang và Du lịch": ["Thời trang", "và Du lịch"],
    "Xây dựng": ["Xây dựng"],
    "ĐT chất lượng cao": ["Đào tạo", "Chất lượng cao"],
    "Điện - Điện tử": ["Điện -", "Điện tử"],
    "Đào tạo Quốc tế": ["Đào tạo", "Quốc tế"],
}